### PR TITLE
US038 - Add a linting check

### PR DESCRIPTION
**Pull request by BlankAmber**
- Adds in linting checks to ensure our code is consistent across the application

Uses the Checkstyle plugin with the default config (sun_checks.xml) and the following suppressions:
- Javadoc
- TodoComment

### CODE REVIEW

**Comment by BlankAmber** [comment]
The workflow runs `mvn clean install` which internally runs `mvn validate`. Proof that the linter works:
(Note that failure is expected as the commit to fix linter errors has yet to be pushed)
Screenshot 2023-12-02 at 15 07 34

**Comment by BlankAmber** [comment]
😄 
Screenshot 2023-12-02 at 15 10 33

**Review by adammarshall745 — APPROVED** [review]

**Review by jkelso662 — APPROVED** [review]
Fab!

**Comment by adammarshall745** [comment]
Screenshot 2023-12-05 at 14 50 25
This has been tested and passed!

**Pull request merged**
